language: python
dist: bionic
os: linux
python:
  - "3.11"
before_install:
  - pip install 'urllib3<2.0'
  - sudo apt-get update
#  - sudo apt-get install -y sqlite3 libsqlite3-dev
  # Verify SQLite version
  - sqlite3 --version

# Define your build steps, for example:
install:
  - pip install -r requirements.txt  # Install dependencies

script:
  - python -m manage.py test
  - python -m black . --check
  - python -m flake8 --ignore=E303,E501 --max-line-length=88
  - python -m coverage run --source=mysite,polls manage.py test

after_success:
  coveralls

deploy:
  provider: elasticbeanstalk
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-2"
  app: "swe1-app"
  env: "test"
  bucket_name: "elasticbeanstalk-us-west-2-466579977483"
# You can add additional steps such as deployment configuration if needed.